# Telemetry Generation (Query Event ID 4625)
# data was analyzed to identify the source address, targeted account, authentication context, and failure information.

# Retrieve failed Windows authentication events generated by the controlled activity.
# Recupera eventos de autenticación fallida generados por la actividad controlada.

Get-WinEvent -FilterHashtable @{
    LogName = "Security"
    Id = 4625
} -MaxEvents 20 |
    Select-Object TimeCreated,Id,Message |
    Format-List
